from pathlib import Path
from PIL import Image
import hashlib,json,subprocess
r=Path('D:/Project/Rogue10m');e=r/'Feature/doc/evidence/unused-file-cleanup-20260928'
def read(n):return json.loads((e/n).read_text(encoding='utf-8-sig'))
def rel(p):return Path(p).resolve().relative_to(r.resolve()).as_posix()
def sha(p):
 h=hashlib.sha256()
 with Path(p).open('rb') as f:
  for block in iter(lambda:f.read(4194304),b''):h.update(block)
 return h.hexdigest()
deps={};files=[];groups=[]
def dep(p):
 p=Path(p);k=rel(p)
 if k not in deps:deps[k]={'path':k,'sha256':sha(p),'bytes':p.stat().st_size}
 return k
for row in read('recreatable-frames.json')['folders']:
 if not row['eligible_for_root_cleanup']:continue
 d=Path(row['folder']);s=Path(row['source_directory']);assert not row['errors']
 script=dep(row['script']);log=dep(row['required_log']);video=dep(row['final_video'])
 probe=json.loads(subprocess.check_output([str(r/'tmp/recorded-reference/decoder/ffprobe.exe'),'-v','error','-select_streams','v:0','-show_entries','stream=codec_name,width,height,nb_frames','-show_entries','format=duration','-of','json',str(r/video)]))
 assert len(probe['streams'])==1 and int(probe['streams'][0]['nb_frames'])==row['frame_count'],(video,probe,row['frame_count'])
 for item in row['recreated_frames']:
  target=d/item['name'];source=s/item['name']
  with Image.open(target) as im:
   assert im.mode=='RGB' and im.size==(1280,720),(str(target),im.mode,im.size)
   assert hashlib.sha256(im.tobytes()).hexdigest()==item['rgb_sha256']
  source_key=dep(source)
  files.append({'original':rel(target),'kind':'regeneratable_frame','bytes':target.stat().st_size,'sha256':sha(target),'source':source_key,'generator':script,'required_log':log,'final_video':video,'rgb_sha256':item['rgb_sha256']})
 groups.append({'folder':rel(d),'frames':row['frame_count'],'bytes':row['bytes'],'generator':script,'required_log':log,'source_directory':rel(s),'final_video':video,'video_probe':probe})
for item in read('reviewed_candidates.json')['files']:
 if item['decision']!='delete_duplicate' or item['original'] in deps:continue
 assert Path(item['original']).suffix.lower() not in {'.py','.ps1','.cmd','.bat','.cpp','.h','.exe','.dll'}
 target=r/item['original'];keep=r/item['keep'];assert sha(target)==sha(keep)==item['sha256'].lower()
 dep(keep); files.append({k:item[k] for k in ('original','keep','bytes','sha256')}|{'kind':'duplicate'})
assert len({x['original'] for x in files})==len(files)
assert not ({x['original'] for x in files}&set(deps))
report={'schema_version':1,'project_root':str(r),'summary':{'files':len(files),'bytes':sum(x['bytes'] for x in files),'duplicates':sum(x['kind']=='duplicate' for x in files),'frames':sum(x['kind']=='regeneratable_frame' for x in files),'frame_folders':len(groups)},'retained_dependencies':list(deps.values()),'frame_groups':groups,'files':files,'restoration':'Duplicate files can be copied byte-for-byte from keep. Frame groups can be regenerated by running generator from project root; full RGB pixels match, compressed PNG byte identity is not claimed. Preserve source screenshots, logs, generators and fonts.'}
(e/'selected-cleanup.json').write_text(json.dumps(report,ensure_ascii=False,indent=2),encoding='utf-8')
print(json.dumps(report['summary']))
